live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x4d4d4d"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "0x14151b"
blue = "0x4d5b86"
cyan = "0x59dffc"
green = "0x1ef956"
magenta = "0xff46b0"
red = "0xff2222"
white = "0xe6e6d1"
yellow = "0xebf85b"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "#1c2841"
foreground = "0xf8f8f2"

[colors.search.focused_match]
background = "0xffb86c"
foreground = "0x44475a"

# [colors.search.footer_bar]
# background = "0x282a36"
# foreground = "0xf8f8f2"

[colors.search.matches]
background = "0x50fa7b"
foreground = "0x44475a"

[colors.selection]
background = "0x44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 12.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "gc"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "C"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "E"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "Up"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "Down"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "Left"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "Right"
mode = "Vi"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key6"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "High"
key = "H"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Middle"
key = "M"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Low"
key = "L"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SemanticLeft"
key = "B"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRight"
key = "W"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "E"
mode = "Vi"

[[keyboard.bindings]]
action = "WordLeft"
key = "B"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRight"
key = "W"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRightEnd"
key = "E"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Bracket"
key = "Key5"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi"
mods = "Shift"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.5

[window.padding]
x = 0
y = 0
